#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="controlIcbf")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertasistencia(asistencia instance);
    partial void Updateasistencia(asistencia instance);
    partial void Deleteasistencia(asistencia instance);
    partial void InsertavanceAcademico(avanceAcademico instance);
    partial void UpdateavanceAcademico(avanceAcademico instance);
    partial void DeleteavanceAcademico(avanceAcademico instance);
    partial void Insertjardine(jardine instance);
    partial void Updatejardine(jardine instance);
    partial void Deletejardine(jardine instance);
    partial void Insertnino(nino instance);
    partial void Updatenino(nino instance);
    partial void Deletenino(nino instance);
    partial void InserttipoUsuario(tipoUsuario instance);
    partial void UpdatetipoUsuario(tipoUsuario instance);
    partial void DeletetipoUsuario(tipoUsuario instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Modelo.Properties.Settings.Default.controlIcbfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<asistencia> asistencias
		{
			get
			{
				return this.GetTable<asistencia>();
			}
		}
		
		public System.Data.Linq.Table<avanceAcademico> avanceAcademicos
		{
			get
			{
				return this.GetTable<avanceAcademico>();
			}
		}
		
		public System.Data.Linq.Table<jardine> jardines
		{
			get
			{
				return this.GetTable<jardine>();
			}
		}
		
		public System.Data.Linq.Table<nino> ninos
		{
			get
			{
				return this.GetTable<nino>();
			}
		}
		
		public System.Data.Linq.Table<tipoUsuario> tipoUsuarios
		{
			get
			{
				return this.GetTable<tipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuarios
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_login")]
		public ISingleResult<sp_loginResult> sp_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, password);
			return ((ISingleResult<sp_loginResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.asistencia")]
	public partial class asistencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _noRegistro;
		
		private string _nIdNino;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _estadoNino;
		
		private EntityRef<nino> _nino;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoRegistroChanging(int value);
    partial void OnnoRegistroChanged();
    partial void OnnIdNinoChanging(string value);
    partial void OnnIdNinoChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnestadoNinoChanging(string value);
    partial void OnestadoNinoChanged();
    #endregion
		
		public asistencia()
		{
			this._nino = default(EntityRef<nino>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noRegistro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int noRegistro
		{
			get
			{
				return this._noRegistro;
			}
			set
			{
				if ((this._noRegistro != value))
				{
					this.OnnoRegistroChanging(value);
					this.SendPropertyChanging();
					this._noRegistro = value;
					this.SendPropertyChanged("noRegistro");
					this.OnnoRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdNino", DbType="VarChar(11)")]
		public string nIdNino
		{
			get
			{
				return this._nIdNino;
			}
			set
			{
				if ((this._nIdNino != value))
				{
					if (this._nino.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnIdNinoChanging(value);
					this.SendPropertyChanging();
					this._nIdNino = value;
					this.SendPropertyChanged("nIdNino");
					this.OnnIdNinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoNino", DbType="VarChar(30)")]
		public string estadoNino
		{
			get
			{
				return this._estadoNino;
			}
			set
			{
				if ((this._estadoNino != value))
				{
					this.OnestadoNinoChanging(value);
					this.SendPropertyChanging();
					this._estadoNino = value;
					this.SendPropertyChanged("estadoNino");
					this.OnestadoNinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nino_asistencia", Storage="_nino", ThisKey="nIdNino", OtherKey="idNino", IsForeignKey=true)]
		public nino nino
		{
			get
			{
				return this._nino.Entity;
			}
			set
			{
				nino previousValue = this._nino.Entity;
				if (((previousValue != value) 
							|| (this._nino.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nino.Entity = null;
						previousValue.asistencias.Remove(this);
					}
					this._nino.Entity = value;
					if ((value != null))
					{
						value.asistencias.Add(this);
						this._nIdNino = value.idNino;
					}
					else
					{
						this._nIdNino = default(string);
					}
					this.SendPropertyChanged("nino");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.avanceAcademico")]
	public partial class avanceAcademico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _noRegsitro;
		
		private string _nIdNino;
		
		private string _anioEscolar;
		
		private string _nivel;
		
		private System.Nullable<int> _nota;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fechaCalificacion;
		
		private EntityRef<nino> _nino;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoRegsitroChanging(int value);
    partial void OnnoRegsitroChanged();
    partial void OnnIdNinoChanging(string value);
    partial void OnnIdNinoChanged();
    partial void OnanioEscolarChanging(string value);
    partial void OnanioEscolarChanged();
    partial void OnnivelChanging(string value);
    partial void OnnivelChanged();
    partial void OnnotaChanging(System.Nullable<int> value);
    partial void OnnotaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaCalificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaCalificacionChanged();
    #endregion
		
		public avanceAcademico()
		{
			this._nino = default(EntityRef<nino>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noRegsitro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int noRegsitro
		{
			get
			{
				return this._noRegsitro;
			}
			set
			{
				if ((this._noRegsitro != value))
				{
					this.OnnoRegsitroChanging(value);
					this.SendPropertyChanging();
					this._noRegsitro = value;
					this.SendPropertyChanged("noRegsitro");
					this.OnnoRegsitroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIdNino", DbType="VarChar(11)")]
		public string nIdNino
		{
			get
			{
				return this._nIdNino;
			}
			set
			{
				if ((this._nIdNino != value))
				{
					if (this._nino.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnIdNinoChanging(value);
					this.SendPropertyChanging();
					this._nIdNino = value;
					this.SendPropertyChanged("nIdNino");
					this.OnnIdNinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anioEscolar", DbType="VarChar(11)")]
		public string anioEscolar
		{
			get
			{
				return this._anioEscolar;
			}
			set
			{
				if ((this._anioEscolar != value))
				{
					this.OnanioEscolarChanging(value);
					this.SendPropertyChanging();
					this._anioEscolar = value;
					this.SendPropertyChanged("anioEscolar");
					this.OnanioEscolarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(10)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this.OnnivelChanging(value);
					this.SendPropertyChanging();
					this._nivel = value;
					this.SendPropertyChanged("nivel");
					this.OnnivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota", DbType="Int")]
		public System.Nullable<int> nota
		{
			get
			{
				return this._nota;
			}
			set
			{
				if ((this._nota != value))
				{
					this.OnnotaChanging(value);
					this.SendPropertyChanging();
					this._nota = value;
					this.SendPropertyChanged("nota");
					this.OnnotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCalificacion", DbType="Date")]
		public System.Nullable<System.DateTime> fechaCalificacion
		{
			get
			{
				return this._fechaCalificacion;
			}
			set
			{
				if ((this._fechaCalificacion != value))
				{
					this.OnfechaCalificacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCalificacion = value;
					this.SendPropertyChanged("fechaCalificacion");
					this.OnfechaCalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nino_avanceAcademico", Storage="_nino", ThisKey="nIdNino", OtherKey="idNino", IsForeignKey=true)]
		public nino nino
		{
			get
			{
				return this._nino.Entity;
			}
			set
			{
				nino previousValue = this._nino.Entity;
				if (((previousValue != value) 
							|| (this._nino.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nino.Entity = null;
						previousValue.avanceAcademicos.Remove(this);
					}
					this._nino.Entity = value;
					if ((value != null))
					{
						value.avanceAcademicos.Add(this);
						this._nIdNino = value.idNino;
					}
					else
					{
						this._nIdNino = default(string);
					}
					this.SendPropertyChanged("nino");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jardines")]
	public partial class jardine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idJardin;
		
		private string _nombre;
		
		private string _direccion;
		
		private string _encargado;
		
		private string _estado;
		
		private EntitySet<nino> _ninos;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidJardinChanging(string value);
    partial void OnidJardinChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnencargadoChanging(string value);
    partial void OnencargadoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public jardine()
		{
			this._ninos = new EntitySet<nino>(new Action<nino>(this.attach_ninos), new Action<nino>(this.detach_ninos));
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJardin", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idJardin
		{
			get
			{
				return this._idJardin;
			}
			set
			{
				if ((this._idJardin != value))
				{
					this.OnidJardinChanging(value);
					this.SendPropertyChanging();
					this._idJardin = value;
					this.SendPropertyChanged("idJardin");
					this.OnidJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(55)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encargado", DbType="VarChar(30)")]
		public string encargado
		{
			get
			{
				return this._encargado;
			}
			set
			{
				if ((this._encargado != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnencargadoChanging(value);
					this.SendPropertyChanging();
					this._encargado = value;
					this.SendPropertyChanged("encargado");
					this.OnencargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jardine_nino", Storage="_ninos", ThisKey="idJardin", OtherKey="jIdJardin")]
		public EntitySet<nino> ninos
		{
			get
			{
				return this._ninos;
			}
			set
			{
				this._ninos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_jardine", Storage="_usuario", ThisKey="encargado", OtherKey="idUsuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.jardines.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.jardines.Add(this);
						this._encargado = value.idUsuario;
					}
					else
					{
						this._encargado = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ninos(nino entity)
		{
			this.SendPropertyChanging();
			entity.jardine = this;
		}
		
		private void detach_ninos(nino entity)
		{
			this.SendPropertyChanging();
			entity.jardine = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ninos")]
	public partial class nino : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idNino;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private string _tipoSangre;
		
		private string _ciudadOrigen;
		
		private string _aIdAcudiente;
		
		private string _telefono;
		
		private string _direccion;
		
		private string _EPS;
		
		private string _jIdJardin;
		
		private string _uIdUsuarioRegistra;
		
		private EntitySet<asistencia> _asistencias;
		
		private EntitySet<avanceAcademico> _avanceAcademicos;
		
		private EntityRef<jardine> _jardine;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNinoChanging(string value);
    partial void OnidNinoChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    partial void OntipoSangreChanging(string value);
    partial void OntipoSangreChanged();
    partial void OnciudadOrigenChanging(string value);
    partial void OnciudadOrigenChanged();
    partial void OnaIdAcudienteChanging(string value);
    partial void OnaIdAcudienteChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnEPSChanging(string value);
    partial void OnEPSChanged();
    partial void OnjIdJardinChanging(string value);
    partial void OnjIdJardinChanged();
    partial void OnuIdUsuarioRegistraChanging(string value);
    partial void OnuIdUsuarioRegistraChanged();
    #endregion
		
		public nino()
		{
			this._asistencias = new EntitySet<asistencia>(new Action<asistencia>(this.attach_asistencias), new Action<asistencia>(this.detach_asistencias));
			this._avanceAcademicos = new EntitySet<avanceAcademico>(new Action<avanceAcademico>(this.attach_avanceAcademicos), new Action<avanceAcademico>(this.detach_avanceAcademicos));
			this._jardine = default(EntityRef<jardine>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNino", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idNino
		{
			get
			{
				return this._idNino;
			}
			set
			{
				if ((this._idNino != value))
				{
					this.OnidNinoChanging(value);
					this.SendPropertyChanging();
					this._idNino = value;
					this.SendPropertyChanged("idNino");
					this.OnidNinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(11)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(11)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoSangre", DbType="VarChar(6)")]
		public string tipoSangre
		{
			get
			{
				return this._tipoSangre;
			}
			set
			{
				if ((this._tipoSangre != value))
				{
					this.OntipoSangreChanging(value);
					this.SendPropertyChanging();
					this._tipoSangre = value;
					this.SendPropertyChanged("tipoSangre");
					this.OntipoSangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudadOrigen", DbType="VarChar(100)")]
		public string ciudadOrigen
		{
			get
			{
				return this._ciudadOrigen;
			}
			set
			{
				if ((this._ciudadOrigen != value))
				{
					this.OnciudadOrigenChanging(value);
					this.SendPropertyChanging();
					this._ciudadOrigen = value;
					this.SendPropertyChanged("ciudadOrigen");
					this.OnciudadOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aIdAcudiente", DbType="VarChar(11)")]
		public string aIdAcudiente
		{
			get
			{
				return this._aIdAcudiente;
			}
			set
			{
				if ((this._aIdAcudiente != value))
				{
					this.OnaIdAcudienteChanging(value);
					this.SendPropertyChanging();
					this._aIdAcudiente = value;
					this.SendPropertyChanged("aIdAcudiente");
					this.OnaIdAcudienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(11)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(55)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPS", DbType="VarChar(100)")]
		public string EPS
		{
			get
			{
				return this._EPS;
			}
			set
			{
				if ((this._EPS != value))
				{
					this.OnEPSChanging(value);
					this.SendPropertyChanging();
					this._EPS = value;
					this.SendPropertyChanged("EPS");
					this.OnEPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jIdJardin", DbType="VarChar(30)")]
		public string jIdJardin
		{
			get
			{
				return this._jIdJardin;
			}
			set
			{
				if ((this._jIdJardin != value))
				{
					if (this._jardine.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnjIdJardinChanging(value);
					this.SendPropertyChanging();
					this._jIdJardin = value;
					this.SendPropertyChanged("jIdJardin");
					this.OnjIdJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uIdUsuarioRegistra", DbType="VarChar(30)")]
		public string uIdUsuarioRegistra
		{
			get
			{
				return this._uIdUsuarioRegistra;
			}
			set
			{
				if ((this._uIdUsuarioRegistra != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuIdUsuarioRegistraChanging(value);
					this.SendPropertyChanging();
					this._uIdUsuarioRegistra = value;
					this.SendPropertyChanged("uIdUsuarioRegistra");
					this.OnuIdUsuarioRegistraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nino_asistencia", Storage="_asistencias", ThisKey="idNino", OtherKey="nIdNino")]
		public EntitySet<asistencia> asistencias
		{
			get
			{
				return this._asistencias;
			}
			set
			{
				this._asistencias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nino_avanceAcademico", Storage="_avanceAcademicos", ThisKey="idNino", OtherKey="nIdNino")]
		public EntitySet<avanceAcademico> avanceAcademicos
		{
			get
			{
				return this._avanceAcademicos;
			}
			set
			{
				this._avanceAcademicos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jardine_nino", Storage="_jardine", ThisKey="jIdJardin", OtherKey="idJardin", IsForeignKey=true)]
		public jardine jardine
		{
			get
			{
				return this._jardine.Entity;
			}
			set
			{
				jardine previousValue = this._jardine.Entity;
				if (((previousValue != value) 
							|| (this._jardine.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jardine.Entity = null;
						previousValue.ninos.Remove(this);
					}
					this._jardine.Entity = value;
					if ((value != null))
					{
						value.ninos.Add(this);
						this._jIdJardin = value.idJardin;
					}
					else
					{
						this._jIdJardin = default(string);
					}
					this.SendPropertyChanged("jardine");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_nino", Storage="_usuario", ThisKey="uIdUsuarioRegistra", OtherKey="idUsuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.ninos.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.ninos.Add(this);
						this._uIdUsuarioRegistra = value.idUsuario;
					}
					else
					{
						this._uIdUsuarioRegistra = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_asistencias(asistencia entity)
		{
			this.SendPropertyChanging();
			entity.nino = this;
		}
		
		private void detach_asistencias(asistencia entity)
		{
			this.SendPropertyChanging();
			entity.nino = null;
		}
		
		private void attach_avanceAcademicos(avanceAcademico entity)
		{
			this.SendPropertyChanging();
			entity.nino = this;
		}
		
		private void detach_avanceAcademicos(avanceAcademico entity)
		{
			this.SendPropertyChanging();
			entity.nino = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoUsuarios")]
	public partial class tipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoUsuario;
		
		private string _descripcionEstado;
		
		private EntitySet<usuario> _usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoUsuarioChanging(int value);
    partial void OnidTipoUsuarioChanged();
    partial void OndescripcionEstadoChanging(string value);
    partial void OndescripcionEstadoChanged();
    #endregion
		
		public tipoUsuario()
		{
			this._usuarios = new EntitySet<usuario>(new Action<usuario>(this.attach_usuarios), new Action<usuario>(this.detach_usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoUsuario
		{
			get
			{
				return this._idTipoUsuario;
			}
			set
			{
				if ((this._idTipoUsuario != value))
				{
					this.OnidTipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idTipoUsuario = value;
					this.SendPropertyChanged("idTipoUsuario");
					this.OnidTipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionEstado", DbType="VarChar(30)")]
		public string descripcionEstado
		{
			get
			{
				return this._descripcionEstado;
			}
			set
			{
				if ((this._descripcionEstado != value))
				{
					this.OndescripcionEstadoChanging(value);
					this.SendPropertyChanging();
					this._descripcionEstado = value;
					this.SendPropertyChanged("descripcionEstado");
					this.OndescripcionEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoUsuario_usuario", Storage="_usuarios", ThisKey="idTipoUsuario", OtherKey="tUsuario")]
		public EntitySet<usuario> usuarios
		{
			get
			{
				return this._usuarios;
			}
			set
			{
				this._usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_usuarios(usuario entity)
		{
			this.SendPropertyChanging();
			entity.tipoUsuario = this;
		}
		
		private void detach_usuarios(usuario entity)
		{
			this.SendPropertyChanging();
			entity.tipoUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idUsuario;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.Nullable<System.DateTime> _fechaNace;
		
		private string _telefono;
		
		private string _direccion;
		
		private string _email;
		
		private System.Nullable<int> _estado;
		
		private System.Nullable<int> _tUsuario;
		
		private string _clave;
		
		private EntitySet<jardine> _jardines;
		
		private EntitySet<nino> _ninos;
		
		private EntityRef<tipoUsuario> _tipoUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(string value);
    partial void OnidUsuarioChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnfechaNaceChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNaceChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnestadoChanging(System.Nullable<int> value);
    partial void OnestadoChanged();
    partial void OntUsuarioChanging(System.Nullable<int> value);
    partial void OntUsuarioChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    #endregion
		
		public usuario()
		{
			this._jardines = new EntitySet<jardine>(new Action<jardine>(this.attach_jardines), new Action<jardine>(this.detach_jardines));
			this._ninos = new EntitySet<nino>(new Action<nino>(this.attach_ninos), new Action<nino>(this.detach_ninos));
			this._tipoUsuario = default(EntityRef<tipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(30)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(30)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNace", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNace
		{
			get
			{
				return this._fechaNace;
			}
			set
			{
				if ((this._fechaNace != value))
				{
					this.OnfechaNaceChanging(value);
					this.SendPropertyChanging();
					this._fechaNace = value;
					this.SendPropertyChanged("fechaNace");
					this.OnfechaNaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(110)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(55)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Int")]
		public System.Nullable<int> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tUsuario", DbType="Int")]
		public System.Nullable<int> tUsuario
		{
			get
			{
				return this._tUsuario;
			}
			set
			{
				if ((this._tUsuario != value))
				{
					if (this._tipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntUsuarioChanging(value);
					this.SendPropertyChanging();
					this._tUsuario = value;
					this.SendPropertyChanged("tUsuario");
					this.OntUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(55)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_jardine", Storage="_jardines", ThisKey="idUsuario", OtherKey="encargado")]
		public EntitySet<jardine> jardines
		{
			get
			{
				return this._jardines;
			}
			set
			{
				this._jardines.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_nino", Storage="_ninos", ThisKey="idUsuario", OtherKey="uIdUsuarioRegistra")]
		public EntitySet<nino> ninos
		{
			get
			{
				return this._ninos;
			}
			set
			{
				this._ninos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoUsuario_usuario", Storage="_tipoUsuario", ThisKey="tUsuario", OtherKey="idTipoUsuario", IsForeignKey=true)]
		public tipoUsuario tipoUsuario
		{
			get
			{
				return this._tipoUsuario.Entity;
			}
			set
			{
				tipoUsuario previousValue = this._tipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipoUsuario.Entity = null;
						previousValue.usuarios.Remove(this);
					}
					this._tipoUsuario.Entity = value;
					if ((value != null))
					{
						value.usuarios.Add(this);
						this._tUsuario = value.idTipoUsuario;
					}
					else
					{
						this._tUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_jardines(jardine entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_jardines(jardine entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_ninos(nino entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_ninos(nino entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
	
	public partial class sp_loginResult
	{
		
		private string _idUsuario;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.Nullable<System.DateTime> _fechaNace;
		
		private string _telefono;
		
		private string _direccion;
		
		private string _email;
		
		private System.Nullable<int> _estado;
		
		private System.Nullable<int> _tUsuario;
		
		private string _clave;
		
		public sp_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(30)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(30)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this._apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNace", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNace
		{
			get
			{
				return this._fechaNace;
			}
			set
			{
				if ((this._fechaNace != value))
				{
					this._fechaNace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(110)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(55)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Int")]
		public System.Nullable<int> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tUsuario", DbType="Int")]
		public System.Nullable<int> tUsuario
		{
			get
			{
				return this._tUsuario;
			}
			set
			{
				if ((this._tUsuario != value))
				{
					this._tUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(55)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this._clave = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
